// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"wwwin-github.cisco.com/eti/swagger-authentication-test/client/models"
)

// NewPostTestParams creates a new PostTestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostTestParams() *PostTestParams {
	return &PostTestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostTestParamsWithTimeout creates a new PostTestParams object
// with the ability to set a timeout on a request.
func NewPostTestParamsWithTimeout(timeout time.Duration) *PostTestParams {
	return &PostTestParams{
		timeout: timeout,
	}
}

// NewPostTestParamsWithContext creates a new PostTestParams object
// with the ability to set a context for a request.
func NewPostTestParamsWithContext(ctx context.Context) *PostTestParams {
	return &PostTestParams{
		Context: ctx,
	}
}

// NewPostTestParamsWithHTTPClient creates a new PostTestParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostTestParamsWithHTTPClient(client *http.Client) *PostTestParams {
	return &PostTestParams{
		HTTPClient: client,
	}
}

/* PostTestParams contains all the parameters to send to the API endpoint
   for the post test operation.

   Typically these are written to a http.Request.
*/
type PostTestParams struct {

	// Body.
	Body *models.Body

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTestParams) WithDefaults() *PostTestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post test params
func (o *PostTestParams) WithTimeout(timeout time.Duration) *PostTestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post test params
func (o *PostTestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post test params
func (o *PostTestParams) WithContext(ctx context.Context) *PostTestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post test params
func (o *PostTestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post test params
func (o *PostTestParams) WithHTTPClient(client *http.Client) *PostTestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post test params
func (o *PostTestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post test params
func (o *PostTestParams) WithBody(body *models.Body) *PostTestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post test params
func (o *PostTestParams) SetBody(body *models.Body) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostTestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
