// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"wwwin-github.cisco.com/eti/swagger-authentication-test/client/models"
)

// PostTestReader is a Reader for the PostTest structure.
type PostTestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostTestCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostTestUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostTestForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostTestCreated creates a PostTestCreated with default headers values
func NewPostTestCreated() *PostTestCreated {
	return &PostTestCreated{}
}

/* PostTestCreated describes a response with status code 201, with default header values.

Success
*/
type PostTestCreated struct {
	Payload *models.OK
}

func (o *PostTestCreated) Error() string {
	return fmt.Sprintf("[POST /test][%d] postTestCreated  %+v", 201, o.Payload)
}
func (o *PostTestCreated) GetPayload() *models.OK {
	return o.Payload
}

func (o *PostTestCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OK)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostTestUnauthorized creates a PostTestUnauthorized with default headers values
func NewPostTestUnauthorized() *PostTestUnauthorized {
	return &PostTestUnauthorized{}
}

/* PostTestUnauthorized describes a response with status code 401, with default header values.

Not authenticated
*/
type PostTestUnauthorized struct {
}

func (o *PostTestUnauthorized) Error() string {
	return fmt.Sprintf("[POST /test][%d] postTestUnauthorized ", 401)
}

func (o *PostTestUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostTestForbidden creates a PostTestForbidden with default headers values
func NewPostTestForbidden() *PostTestForbidden {
	return &PostTestForbidden{}
}

/* PostTestForbidden describes a response with status code 403, with default header values.

Access token does not have the required scope
*/
type PostTestForbidden struct {
}

func (o *PostTestForbidden) Error() string {
	return fmt.Sprintf("[POST /test][%d] postTestForbidden ", 403)
}

func (o *PostTestForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
