// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"wwwin-github.cisco.com/eti/swagger-authentication-test/server/models"
)

// PostTestCreatedCode is the HTTP code returned for type PostTestCreated
const PostTestCreatedCode int = 201

/*PostTestCreated Success

swagger:response postTestCreated
*/
type PostTestCreated struct {

	/*
	  In: Body
	*/
	Payload *models.OK `json:"body,omitempty"`
}

// NewPostTestCreated creates PostTestCreated with default headers values
func NewPostTestCreated() *PostTestCreated {

	return &PostTestCreated{}
}

// WithPayload adds the payload to the post test created response
func (o *PostTestCreated) WithPayload(payload *models.OK) *PostTestCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post test created response
func (o *PostTestCreated) SetPayload(payload *models.OK) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTestCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostTestUnauthorizedCode is the HTTP code returned for type PostTestUnauthorized
const PostTestUnauthorizedCode int = 401

/*PostTestUnauthorized Not authenticated

swagger:response postTestUnauthorized
*/
type PostTestUnauthorized struct {
}

// NewPostTestUnauthorized creates PostTestUnauthorized with default headers values
func NewPostTestUnauthorized() *PostTestUnauthorized {

	return &PostTestUnauthorized{}
}

// WriteResponse to the client
func (o *PostTestUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostTestForbiddenCode is the HTTP code returned for type PostTestForbidden
const PostTestForbiddenCode int = 403

/*PostTestForbidden Access token does not have the required scope

swagger:response postTestForbidden
*/
type PostTestForbidden struct {
}

// NewPostTestForbidden creates PostTestForbidden with default headers values
func NewPostTestForbidden() *PostTestForbidden {

	return &PostTestForbidden{}
}

// WriteResponse to the client
func (o *PostTestForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
