apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https-client
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    metadata:
      labels:
        app: https-client
    spec:
      containers:
        - name: client-allow
          image: idanfrim/https-test
          args: ["run-client"]
          env:
            - name: HOST
              value: "server:8433"
            - name: API_KEY
              value: "allow"
            - name: CLIENT_CALLS_NUMBER
              value: "100"
        - name: client-block
          image: idanfrim/https-test
          args: ["run-client"]
          env:
            - name: HOST
              value: "server:8433"
            - name: API_KEY
              value: "block"
            - name: CLIENT_CALLS_NUMBER
              value: "100"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-client
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    metadata:
      labels:
        app: http-client
    spec:
      containers:
        - name: client-allow
          image: idanfrim/https-test
          args: ["run-client"]
          env:
            - name: HOST
              value: "server:8080"
            - name: API_KEY
              value: "allow"
            - name: CLIENT_CALLS_NUMBER
              value: "100"
            - name: DISABLE_TLS
              value: "true"
        - name: client-block
          image: idanfrim/https-test
          args: ["run-client"]
          env:
            - name: HOST
              value: "server:8080"
            - name: API_KEY
              value: "block"
            - name: CLIENT_CALLS_NUMBER
              value: "100"
            - name: DISABLE_TLS
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
    - port: 8433
      name: https
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: certs
          secret:
            secretName: https-test-certs
      containers:
        - name: server
          image: idanfrim/https-test
          args: ["run-server"]
          env:
            - name: TLS_CERTIFICATE
              value: "/etc/certs/tls.crt"
            - name: TLS_PRIVATE_KEY
              value: "/etc/certs/tls.key"
          ports:
            - containerPort: 8080
            - containerPort: 8433
          volumeMounts:
            - mountPath: /etc/certs
              name: certs
